services:
  web:
    container_name: hifi
    build: .
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

networks:
  default:
    driver: bridge
